### ISSUE TITLE
Killed during loaddata

### ISSUE THREAD

**Issue by lp-kawai** [dipakkr/3d-cnn-action-recognition#5]
I tried to run 3dCNN-v2/3dcnn.py.
python3 3dcnn.py --batch 4 --epoch 100 --videos /home/user/3d-cnn-action-recognition/data2/ --nclass 101 --output 3dcnnresult/ --color False --skip False
In the middle of loading data, it suddenly Killed.
(Only "Killed" showed)
I used UCF101 dataset.
Why this happens?

**Comment by lp-kawai** [comment]
I found frame_script.py not extract 10 frames but more.
What is the expected output?

**Comment by dipakkr** [comment]
@p-kawai you should debug the file frame_script.py.

**Comment by lp-kawai** [comment]
@dipakkr Thank you for your reply. I changed frame_script.py and it worked.
