### ISSUE TITLE
Brief on V2

### ISSUE THREAD

**Issue by DecentMakeover** [dipakkr/3d-cnn-action-recognition#7]
Hi 

Thanks  a lot for sharing your work!

Could you please tell me what is the difference between the main 3dcnn.py and the one in 3dcnnv2.

Thanks

**Comment by dipakkr** [comment]
Hey @DecentMakeover, 

I am glad you find it useful!

The model(structure) is more optimized in v2 compared to v1 and well documented for understanding.

**Comment by DecentMakeover** [comment]
okay Thanks for your response.
